# Generated by Django 6.0.4 on 2026-06-26 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_categories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='categories',
        ),
    ]
