# Generated by Django 6.0.4 on 2026-06-26 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='description',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='image',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='price',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='video',
        ),
    ]
