# Generated by Django 6.0.4 on 2026-06-26 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0002_remove_categories_description_and_more'),
        ('product_app', '0005_product_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='categories',
            new_name='Category',
        ),
    ]
