# Generated by Django 6.0.5 on 2026-06-12 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costomer_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costomer',
            name='email',
        ),
    ]
