# Generated by Django 6.0.5 on 2026-06-25 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costomer_app', '0002_remove_costomer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costomer',
            name='last_name',
        ),
    ]
